Revert "Update GeoTools"
This reverts commit 2d834c1369a3c3a6987f39faff07ef8a45019916.

/home/dan/IdeaUltProjects/approach-minder/analysis/src/main/scala/com/dmanchester/approachminder/GeographicCalculator.scala:10:12
object opengis is not a member of package org
import org.opengis.referencing.operation.MathTransform